export enum StatusProjeto {
    CRIADO ='CRIADO',
    PLANEJAMENTO ='PLANEJAMENTO',
    ENVIADO ='ENVIADO',
    ENTREGUE ='ENTREGUE',
    INSTALADO ='INSTALADO',
    FINALIZADO ='FINALIZADO',
    CANCELADO ='CANCELADO'
}

